# Generated by Django 4.2.1 on 2023-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_full', models.CharField(blank=True, max_length=100)),
                ('name_cn', models.CharField(blank=True, max_length=40)),
                ('nation', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('born', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='book.author')),
                ('tags', models.ManyToManyField(related_name='books', to='tag.tag')),
            ],
        ),
    ]
