# Generated by Django 4.2.1 on 2023-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_completed_book_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
