# Generated by Django 4.2.1 on 2023-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='adsfadsf', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(default='adf', unique=True),
            preserve_default=False,
        ),
    ]
